# Generated by Django 4.2.7 on 2025-09-22 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('absence', 'Absence Alert'), ('daily_absence', 'Daily Absence Alert'), ('teacher_report', 'Teacher Report'), ('late', 'Late Arrival'), ('report', 'Attendance Report'), ('general', 'General')], default='general', max_length=20),
        ),
    ]
