# Generated by Django 4.2.7 on 2025-09-30 16:37

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_add_new_notification_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='classroom',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='classroom',
            name='radius_meters',
            field=models.PositiveIntegerField(default=50),
        ),
        migrations.CreateModel(
            name='AttendanceRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Denied'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('method', models.CharField(choices=[('gps', 'GPS'), ('qr', 'QR'), ('wifi', 'WiFi')], default='gps', max_length=20)),
                ('student_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('student_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_attendance_requests', to='attendance.teacher')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_requests', to='attendance.classroom')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_requests', to='attendance.student')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
