# Generated by Django 4.2.7 on 2025-09-30 18:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_classroom_latitude_classroom_longitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAuth',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('token', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auth', to='attendance.student')),
            ],
        ),
        migrations.CreateModel(
            name='SelfAttendanceWindow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='self_windows', to='attendance.classroom')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='self_windows', to='attendance.teacher')),
            ],
            options={
                'indexes': [models.Index(fields=['classroom', 'expires_at', 'is_active'], name='attendance__classro_2efa53_idx')],
            },
        ),
    ]
